## !/usr/bin/env python3

import os

def avg_title_len(corpName, corpPath=None):
    """
    Reads through a title corpus and computes the average title length in words.

    Inputs:
        >> corpName: the name of the raw text file that has one title per line
        >> corpPath: the directory path in which the corpName file is located, if
        you are running the script from the same file location you do not need
        to supply this variable

    The output generated by this is meant to be used as an input for a title
    generator.
    """

    if corpPath != None:
        path = os.path.join(corpPath, corpName)
    else:
        path = corpName

    with open(path, 'r') as f:
        text = f.readlines()

    total_len = 0
    n_titles = 0

    for row in text:
        if len(row) > 1:
            words = row.split()
            word_len = len(words)
            total_len += word_len
            n_titles += 1
        else:
            continue

    avg_len = int(total_len / n_titles)
    return avg_len
